typography_spectrum: 0.19321584445424378
content_rating:
  adult: false
color:
  brandStrength: 0.6180489177349955
  lightness: 0.35027395584620535
  saturation: 0.45706154499202967
  rhythmicContrast: 0.644913189811632
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.3622979561332613
author:
  name: Peter Roth
  email: info@spechtshaardt.de
name: foodandlifelovershotel
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/d97a517f-a66a-47ff-b5d7-ac4f36559e3c.jpg'
title: Spechtshaardt - your hotel in the spessart
